# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='discount.Discount')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='product_pro_code_f66008_idx'),
        ),
    ]
